# Generated by Django 5.0.1 on 2026-08-31 13:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("constitutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable title for the proposal.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the proposal.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        help_text="The type of action being proposed (e.g., 'CREATE_PROPOSAL').",
                        max_length=100,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "target_resource",
                    models.CharField(
                        help_text="The resource or entity the action targets.",
                        max_length=100,
                        verbose_name="Target Resource",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary JSON data associated with the action.",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("EXECUTED", "Executed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        help_text="Current lifecycle status of the proposal.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "policy_decision",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the policy engine decision.",
                        null=True,
                        verbose_name="Policy Decision",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "constitution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a specific constitution.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="constitutions.constitution",
                        verbose_name="Constitution",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the proposal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal",
                "verbose_name_plural": "Proposals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="proposals_p_status_3eda73_idx"
                    ),
                    models.Index(
                        fields=["created_by", "status"], name="proposals_p_created_d8c2ec_idx"
                    ),
                ],
            },
        ),
    ]
