# Generated by Django 5.0.1 on 2026-09-14 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("constitutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="constitution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who owns this constitution.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constitutions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="constitution",
            name="name",
            field=models.CharField(
                help_text="Human-readable name of the constitution.",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AddIndex(
            model_name="constitution",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_constitution_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="constitution",
            index=models.Index(fields=["user", "is_active"], name="idx_constitution_user_active"),
        ),
        migrations.AddConstraint(
            model_name="constitution",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_constitution_name_per_user"
            ),
        ),
    ]
