# Generated by Django 5.0.1 on 2026-09-01 12:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("APPROVAL_REQUESTED", "Approval Requested"),
                            ("PROPOSAL_APPROVED", "Proposal Approved"),
                            ("PROPOSAL_DENIED", "Proposal Denied"),
                            ("PROPOSAL_EXECUTED", "Proposal Executed"),
                            ("PROPOSAL_CANCELLED", "Proposal Cancelled"),
                            ("SYSTEM", "System"),
                        ],
                        help_text="The category of the notification.",
                        max_length=50,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional related entity model name.",
                        max_length=100,
                        verbose_name="Entity Type",
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Optional UUID of the related entity.",
                        null=True,
                        verbose_name="Entity ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short human-readable title.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed notification message.",
                        verbose_name="Message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UNREAD", "Unread"), ("READ", "Read"), ("ARCHIVED", "Archived")],
                        default="UNREAD",
                        help_text="Current notification status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the notification was marked as read.",
                        null=True,
                        verbose_name="Read At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user receiving the notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"], name="notificatio_recipie_e285de_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="notificatio_entity__950da6_idx"
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                ],
            },
        ),
    ]
