# Generated by Django 5.0.1 on 2026-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("APPROVAL_REQUESTED", "Approval Requested"),
                    ("PROPOSAL_APPROVED", "Proposal Approved"),
                    ("PROPOSAL_DENIED", "Proposal Denied"),
                    ("PROPOSAL_EXECUTED", "Proposal Executed"),
                    ("PROPOSAL_CANCELLED", "Proposal Cancelled"),
                    ("AGREEMENT_ACTIVATED", "Agreement Activated"),
                    ("AGREEMENT_COMPLETED", "Agreement Completed"),
                    ("AGREEMENT_TERMINATED", "Agreement Terminated"),
                    ("SYSTEM", "System"),
                ],
                help_text="The category of the notification.",
                max_length=50,
                verbose_name="Notification Type",
            ),
        ),
    ]
