# Generated by Django 5.0.1 on 2026-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("APPROVAL_REQUESTED", "Approval Requested"),
                    ("PROPOSAL_APPROVED", "Proposal Approved"),
                    ("PROPOSAL_DENIED", "Proposal Denied"),
                    ("PROPOSAL_EXECUTED", "Proposal Executed"),
                    ("PROPOSAL_CANCELLED", "Proposal Cancelled"),
                    ("AGREEMENT_ACTIVATED", "Agreement Activated"),
                    ("AGREEMENT_COMPLETED", "Agreement Completed"),
                    ("AGREEMENT_TERMINATED", "Agreement Terminated"),
                    ("NEGOTIATION_STARTED", "Negotiation Started"),
                    ("NEGOTIATION_AGREED", "Negotiation Agreed"),
                    ("OFFER_RECEIVED", "Offer Received"),
                    ("OFFER_ACCEPTED", "Offer Accepted"),
                    ("OFFER_REJECTED", "Offer Rejected"),
                    ("COMMENT_ADDED", "Comment Added"),
                    ("SYSTEM", "System"),
                ],
                help_text="The category of the notification.",
                max_length=50,
                verbose_name="Notification Type",
            ),
        ),
    ]
