# Generated by Django 5.0.1 on 2026-09-04 13:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the agent.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the agent's purpose.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("AUTO_PROPOSER", "Auto Proposer"),
                            ("AUTO_APPROVER", "Auto Approver"),
                            ("MONITOR", "Monitor"),
                            ("CUSTOM", "Custom"),
                        ],
                        help_text="The category of agent behavior.",
                        max_length=50,
                        verbose_name="Agent Type",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration specific to the agent type.",
                        verbose_name="Config",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the agent is currently active.",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who created the agent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent_type", "is_active"], name="agents_agen_agent_t_df2b4c_idx"
                    ),
                    models.Index(
                        fields=["created_by", "is_active"], name="agents_agen_created_0354ca_idx"
                    ),
                ],
            },
        ),
    ]
