# Generated by Django 5.0.1 on 2026-09-04 13:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the rule.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("ON_PROPOSAL_CREATED", "On Proposal Created"),
                            ("ON_PROPOSAL_SUBMITTED", "On Proposal Submitted"),
                            ("ON_PROPOSAL_STATUS_CHANGED", "On Proposal Status Changed"),
                            ("ON_SCHEDULE", "On Schedule"),
                            ("MANUAL", "Manual"),
                        ],
                        help_text="The event that triggers the rule.",
                        max_length=50,
                        verbose_name="Trigger Type",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON condition that must be met for the rule to fire.",
                        verbose_name="Condition",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE_PROPOSAL", "Create Proposal"),
                            ("APPROVE_PROPOSAL", "Approve Proposal"),
                            ("REJECT_PROPOSAL", "Reject Proposal"),
                            ("ADD_COMMENT", "Add Comment"),
                            ("NOTIFY", "Notify"),
                            ("CUSTOM", "Custom"),
                        ],
                        help_text="The action the agent executes.",
                        max_length=50,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON configuration for the action.",
                        verbose_name="Action Config",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Priority for ordering rule evaluation. Lower runs first.",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the rule is currently active.",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent that owns this rule.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="agents.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who created the rule.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation Rule",
                "verbose_name_plural": "Automation Rules",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "is_active"], name="agents_auto_agent_i_2c4d9d_idx"
                    ),
                    models.Index(
                        fields=["trigger_type", "is_active"], name="agents_auto_trigger_c711a5_idx"
                    ),
                ],
            },
        ),
    ]
