# Generated by Django 5.0.1 on 2026-09-02 13:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("Proposal", "Proposal"),
                            ("Agreement", "Agreement"),
                            ("Negotiation", "Negotiation"),
                        ],
                        help_text="The type of entity being commented on.",
                        max_length=50,
                        verbose_name="Entity Type",
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        help_text="The UUID of the entity being commented on.",
                        verbose_name="Entity ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The comment text.", verbose_name="Content"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The user who wrote the comment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent comment for threaded replies.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="negotiations.comment",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="negotiation_entity__e413ad_idx"
                    ),
                    models.Index(
                        fields=["author", "created_at"], name="negotiation_author__a3f015_idx"
                    ),
                ],
            },
        ),
    ]
