# Generated by Django 5.0.1 on 2026-09-02 14:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("negotiations", "0001_initial"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Negotiation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable title for the negotiation.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the negotiation context.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("AGREED", "Agreed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        help_text="Current lifecycle status of the negotiation.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "initiated_by",
                    models.ForeignKey(
                        help_text="The user who initiated the negotiation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_negotiations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiated By",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="The proposal being negotiated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiations",
                        to="proposals.proposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negotiation",
                "verbose_name_plural": "Negotiations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NegotiationOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured JSON terms of the offer.",
                        verbose_name="Terms",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        help_text="Current status of the offer.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Sequential round number within the negotiation.",
                        verbose_name="Round Number",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes accompanying the offer.",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "negotiation",
                    models.ForeignKey(
                        help_text="The negotiation this offer belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="negotiations.negotiation",
                        verbose_name="Negotiation",
                    ),
                ),
                (
                    "offered_by",
                    models.ForeignKey(
                        help_text="The user making the offer.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negotiation_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Offered By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negotiation Offer",
                "verbose_name_plural": "Negotiation Offers",
                "ordering": ["negotiation", "-round_number", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["status", "created_at"], name="negotiation_status_096eb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="negotiation",
            index=models.Index(
                fields=["proposal", "status"], name="negotiation_proposa_06976d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="negotiationoffer",
            index=models.Index(
                fields=["negotiation", "status"], name="negotiation_negotia_9f890b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="negotiationoffer",
            index=models.Index(
                fields=["offered_by", "created_at"], name="negotiation_offered_146795_idx"
            ),
        ),
    ]
