# Generated by Django 5.0.1 on 2026-09-01 12:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("PROPOSAL_CREATED", "Proposal Created"),
                            ("PROPOSAL_SUBMITTED", "Proposal Submitted"),
                            ("PROPOSAL_APPROVED", "Proposal Approved"),
                            ("PROPOSAL_DENIED", "Proposal Denied"),
                            ("PROPOSAL_EXECUTED", "Proposal Executed"),
                            ("PROPOSAL_CANCELLED", "Proposal Cancelled"),
                            ("APPROVAL_REQUESTED", "Approval Requested"),
                            ("APPROVAL_APPROVED", "Approval Approved"),
                            ("APPROVAL_REJECTED", "Approval Rejected"),
                            ("APPROVAL_CANCELLED", "Approval Cancelled"),
                            ("POLICY_RULE_CREATED", "Policy Rule Created"),
                            ("POLICY_RULE_UPDATED", "Policy Rule Updated"),
                            ("POLICY_RULE_DELETED", "Policy Rule Deleted"),
                        ],
                        help_text="The type of action performed.",
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="The model name of the affected entity.",
                        max_length=100,
                        verbose_name="Entity Type",
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        help_text="The UUID of the affected entity.", verbose_name="Entity ID"
                    ),
                ),
                (
                    "old_state",
                    models.JSONField(
                        blank=True,
                        help_text="Previous state before the transition.",
                        null=True,
                        verbose_name="Old State",
                    ),
                ),
                (
                    "new_state",
                    models.JSONField(
                        blank=True,
                        help_text="New state after the transition.",
                        null=True,
                        verbose_name="New State",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the action.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the actor.",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="User agent string from the request.",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of the action.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action (null for system actions).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="audit_audit_entity__9535bf_idx"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="audit_audit_action_766c6d_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="audit_audit_actor_i_ec0f72_idx"
                    ),
                ],
            },
        ),
    ]
