# Generated by Django 5.0.1 on 2026-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("PROPOSAL_CREATED", "Proposal Created"),
                    ("PROPOSAL_SUBMITTED", "Proposal Submitted"),
                    ("PROPOSAL_APPROVED", "Proposal Approved"),
                    ("PROPOSAL_DENIED", "Proposal Denied"),
                    ("PROPOSAL_EXECUTED", "Proposal Executed"),
                    ("PROPOSAL_CANCELLED", "Proposal Cancelled"),
                    ("APPROVAL_REQUESTED", "Approval Requested"),
                    ("APPROVAL_APPROVED", "Approval Approved"),
                    ("APPROVAL_REJECTED", "Approval Rejected"),
                    ("APPROVAL_CANCELLED", "Approval Cancelled"),
                    ("POLICY_RULE_CREATED", "Policy Rule Created"),
                    ("POLICY_RULE_UPDATED", "Policy Rule Updated"),
                    ("POLICY_RULE_DELETED", "Policy Rule Deleted"),
                    ("AGREEMENT_CREATED", "Agreement Created"),
                    ("AGREEMENT_ACTIVATED", "Agreement Activated"),
                    ("AGREEMENT_SUSPENDED", "Agreement Suspended"),
                    ("AGREEMENT_COMPLETED", "Agreement Completed"),
                    ("AGREEMENT_TERMINATED", "Agreement Terminated"),
                    ("AGREEMENT_AMENDED", "Agreement Amended"),
                    ("NEGOTIATION_CREATED", "Negotiation Created"),
                    ("NEGOTIATION_STARTED", "Negotiation Started"),
                    ("NEGOTIATION_AGREED", "Negotiation Agreed"),
                    ("NEGOTIATION_FAILED", "Negotiation Failed"),
                    ("NEGOTIATION_CANCELLED", "Negotiation Cancelled"),
                    ("OFFER_CREATED", "Offer Created"),
                    ("OFFER_ACCEPTED", "Offer Accepted"),
                    ("OFFER_REJECTED", "Offer Rejected"),
                    ("OFFER_WITHDRAWN", "Offer Withdrawn"),
                    ("COMMENT_ADDED", "Comment Added"),
                    ("COMMENT_DELETED", "Comment Deleted"),
                ],
                help_text="The type of action performed.",
                max_length=50,
                verbose_name="Action",
            ),
        ),
    ]
