# Generated by Django 5.0.1 on 2026-08-31 13:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_role",
                    models.CharField(
                        help_text="The role authorized to approve this request (e.g., 'manager').",
                        max_length=100,
                        verbose_name="Required Role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the approval request.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the decision.",
                        null=True,
                        verbose_name="Decided At",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes provided by the approver.",
                        verbose_name="Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user assigned to approve this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the approval decision.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Decided By",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="The proposal requiring approval.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to="proposals.proposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Request",
                "verbose_name_plural": "Approval Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="approvals_a_status_dd1e4e_idx"
                    ),
                    models.Index(
                        fields=["proposal", "status"], name="approvals_a_proposa_dd6b5f_idx"
                    ),
                    models.Index(
                        fields=["required_role", "status"], name="approvals_a_require_3cd76c_idx"
                    ),
                ],
            },
        ),
    ]
