# Generated by Django 5.0.1 on 2026-08-29 13:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("constitutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the rule.",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of what the rule enforces.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "condition",
                    models.JSONField(
                        help_text="JSON structure defining when the rule applies. Example: {'field': 'amount', 'operator': '>', 'value': 10000}",
                        verbose_name="Condition",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ALLOW", "Allow"),
                            ("DENY", "Deny"),
                            ("REQUIRE_APPROVAL", "Require Approval"),
                        ],
                        help_text="What action to take when the condition is met.",
                        max_length=20,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        help_text="The risk level associated with this rule.",
                        max_length=10,
                        verbose_name="Risk Level",
                    ),
                ),
                (
                    "requires_approval_from",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of roles or user UUIDs required for approval. Only used when action_type is REQUIRE_APPROVAL.",
                        verbose_name="Requires Approval From",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Execution priority (lower = evaluated first).",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the rule is currently active.",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "constitution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a specific constitution.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_rules",
                        to="constitutions.constitution",
                        verbose_name="Constitution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Rule",
                "verbose_name_plural": "Policy Rules",
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"], name="policies_po_is_acti_ff6612_idx"
                    ),
                    models.Index(
                        fields=["constitution", "is_active"], name="policies_po_constit_cedb04_idx"
                    ),
                ],
            },
        ),
    ]
