# Generated by Django 5.0.1 on 2026-09-07 13:54

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the subscription.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The target URL to receive webhook payloads.",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        default="97b669bbc4c9a0eb0bb8d7eb7bb648fe327394133bef6da7550a52d351ad926d",
                        help_text="Secret key used to generate HMAC signatures.",
                        max_length=128,
                        verbose_name="Secret",
                    ),
                ),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("PROPOSAL_CREATED", "Proposal Created"),
                                ("PROPOSAL_STATUS_CHANGED", "Proposal Status Changed"),
                                ("APPROVAL_REQUESTED", "Approval Requested"),
                                ("APPROVAL_RESOLVED", "Approval Resolved"),
                                ("AGREEMENT_ACTIVATED", "Agreement Activated"),
                                ("AGREEMENT_TERMINATED", "Agreement Terminated"),
                                ("NEGOTIATION_STARTED", "Negotiation Started"),
                                ("NEGOTIATION_AGREED", "Negotiation Agreed"),
                                ("NEGOTIATION_FAILED", "Negotiation Failed"),
                            ],
                            max_length=50,
                        ),
                        blank=True,
                        default=list,
                        help_text="List of event types this subscription listens to.",
                        size=None,
                        verbose_name="Events",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the subscription is currently active.",
                        verbose_name="Is Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who created the subscription.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Subscription",
                "verbose_name_plural": "Webhook Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active"], name="webhooks_we_is_acti_629020_idx")
                ],
            },
        ),
    ]
