# Generated by Django 5.0.1 on 2026-09-10 13:00

from django.db import migrations, models

import apps.webhooks.models.webhook_subscription


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0002_alter_webhooksubscription_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooksubscription",
            name="secret",
            field=models.CharField(
                default=apps.webhooks.models.webhook_subscription.generate_webhook_secret,
                help_text="Secret key used to generate HMAC signatures.",
                max_length=128,
                verbose_name="Secret",
            ),
        ),
    ]
