# Generated by Django 5.0.1 on 2026-09-01 13:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("constitutions", "0001_initial"),
        ("proposals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable title for the agreement.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the agreement.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="DRAFT",
                        help_text="Current lifecycle status of the agreement.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "terms",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured JSON terms of the agreement.",
                        verbose_name="Terms",
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when the agreement becomes active.",
                        null=True,
                        verbose_name="Effective Date",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional date when the agreement expires.",
                        null=True,
                        verbose_name="Expiration Date",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "constitution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a specific constitution.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agreements",
                        to="constitutions.constitution",
                        verbose_name="Constitution",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the agreement.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the originating proposal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agreements",
                        to="proposals.proposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement",
                "verbose_name_plural": "Agreements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="agreements__status_9db6f9_idx"
                    ),
                    models.Index(
                        fields=["created_by", "status"], name="agreements__created_b391bc_idx"
                    ),
                    models.Index(
                        fields=["effective_date", "expiration_date"],
                        name="agreements__effecti_5048c9_idx",
                    ),
                ],
            },
        ),
    ]
