# Generated by Django 5.0.1 on 2026-09-01 14:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agreements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        help_text="Sequential version number, unique per agreement.",
                        verbose_name="Version Number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Snapshot of the agreement title at this version.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "terms",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of the agreement terms at this version.",
                        verbose_name="Terms",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of why this version was created.",
                        verbose_name="Change Reason",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "agreement",
                    models.ForeignKey(
                        help_text="The agreement this version belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="agreements.agreement",
                        verbose_name="Agreement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this version.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement Version",
                "verbose_name_plural": "Agreement Versions",
                "ordering": ["agreement", "-version_number"],
                "indexes": [
                    models.Index(
                        fields=["agreement", "version_number"],
                        name="agreements__agreeme_7a3f40_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agreementversion",
            constraint=models.UniqueConstraint(
                fields=("agreement", "version_number"), name="unique_agreement_version_number"
            ),
        ),
    ]
