# Generated by Django 5.0.1 on 2026-09-05 13:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0002_automationrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the job.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="The Celery task name or job identifier.",
                        max_length=255,
                        verbose_name="Task Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        help_text="Current execution status.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        help_text="When the job was scheduled to run.", verbose_name="Scheduled For"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job actually started.",
                        null=True,
                        verbose_name="Started At",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job finished.",
                        null=True,
                        verbose_name="Finished At",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="JSON result of the execution.",
                        null=True,
                        verbose_name="Result",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if the job failed.",
                        verbose_name="Error",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "automation_rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the automation rule being executed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_jobs",
                        to="agents.automationrule",
                        verbose_name="Automation Rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Job",
                "verbose_name_plural": "Scheduled Jobs",
                "ordering": ["-scheduled_for"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"], name="scheduling__status_eb48a0_idx"
                    ),
                    models.Index(
                        fields=["task_name", "scheduled_for"], name="scheduling__task_na_2ae301_idx"
                    ),
                ],
            },
        ),
    ]
